eureka:
  instance:
    preferIpAddress: 'true'
  client:
    serviceUrl:
      defaultZone: http://admin:admin@${app.eureka-server}:8761/eureka
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: '36000000'
spring:
  mail:
    host: smtp.gmail.com
    username: shailesh15.sr@gmail.com
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: fyip ptml dazl bopd
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: Google
            client-secret: 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
            client-id: 725913954560-902evmsbbku9gu3q1qnvl260qrmkaf1d.apps.googleusercontent.com
    application:
      secret-key: 76664BA19299AA93985AD1AD7CB33
  jpa:
    hibernate:
      ddl-auto: update
  application:
    description: Authentication of Matrimony Application
app:
  eureka-server: localhost
custom:
  security:
    otp:
      code:
        length: '6'
      expiry:
        time: '300000'
