spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:shaileshrakhade/matrimony-config.git
#          username: shaileshrakhade
#          password: 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
#          default-label: "master"
          ignoreLocalSshSettings: true
          hostKey: 127.0.0.1
          hostKeyAlgorithm: ssh-rsa
          privateKey: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKAIBAAKCAgEAvT6WxDJKI1tVwHs8LXf3lAYgwOI9Q3JyI15KcjOnwpWGnNQ9
            lJdBPg4XviUItNHg4ljS6iQatFya10FqMbos0RH+X0urQmpm38k54xEt7dqcVT5o
            vnyDrHZuY0LHJRYGosmHzeCjMjkRvIa/L6GmxUx0EFo1m8K2Z+xGscpyEVwyzFJs
            qG5Kn3F9LPxONfkmpvShkW8OOgyF1q/xbN+6iqznrmx8ig04ZXY9ih+viF/2tYi+
            VkWnivHNnypnU5rNyqmNXM11PkVaOjiPB+ZiH+IDSYde5cAhQewADqArx15aggPT
            +c8D515R8UVvuYVi5s7J8LC7vlfmmiCuoi5zEy9bitz+GcwPRV9sK7IeR40Ewrk7
            9CkCfNgoh1nk0hj1nwOyTz8i/ebcwlIGRKk1sET53qKI+hYCZ4r0NfiWV6EFHtiY
            k3g6ZM7D89DHsR5x1/CWhvY6aLTKAgoEseuxNz0kji1ANfBOVc3AAk0QV0nYOi5P
            8hZ6mPNVIgpAh67j6mjLWOkNKpU71w2a8D5QKC1paiAjVKQb8instrYcofEzLdwk
            SUk2BgrGVuxX9JbPLSLYmM31okN4+eiG3jtQMx84wkoY5WhS0B5n0nhTIunJK9qq
            wZyd5j4lTFTMqAhmaL76B8p2vb3aijpPS/YcPmv4Xo6x6putuk9n9SXBYT8CAwEA
            AQKCAgALKpVE0F7VhT8jE2JyoGCIaHAoUXEh+K/JbHfiEzAz6BTATjmv+djMq5I1
            EwRXfwbQ9ELFtAmrWMd+Kgr1EjIwx+oFf3aEfbjCPaJfxpS6MysEUKFnk/tFAtvy
            mW8cvhb4JgIQYM/gV8O3JxBC5Dvt6lvy1w/QuAWBTkzBktt2MMWCjt6AdbmLfOvQ
            6rZGswPX2BlsdmwVesWu7ETHks/z/M3S2e3jS3JncjmhW8tEtbzd60qn1oZTSX9D
            hAICyeCYs7Z2olznprnzM4ElCzABB5oADa/IyLRtqlo6grLymZunjkhEtjVZwpP9
            M4arILa8PblmrVb2nUMrFwCW6zy4694hlBEQRCN5jJGBa1enWWKpjUEw0CStY39d
            lpzWpvVQN0jDbGq0GrG7bNEnT8oUDYHLheKu8uWGoPUekeCMGZDkZmSbyq8p9Xgh
            CqmR5FR0JLPSeGdpk/g4y08Zdyx5eHh2yP1gmbqlHxvN20TpeaMcNna9xlXz29ie
            aUwPAQqGPr07ESEeCj1Y/AN/c+5wdXHWznM9U5csPBGGDMtNvx1fjRLX7Qw2CRNw
            XFb0Zst+krwzhyxUYi4zXzNCoymJCnDRX8Y0hQsMpTZTT+Q8XmVmeQj39Y89TuPo
            YcCp2SqEbIrUO0Kdxb/8xuY8DZxpDbar0fYNdT+0Tv001i2MkQKCAQEA+6SJJR4a
            YyRma2n6x/8ivvpOIitJ+ON66TADZ7G40jxN+N2XEFHHv7k7KHF6E5ehcwg9EfFk
            1/mwfUMTMeG4IqNMi7t4On2kZNIsTm5vLnkDaycRYY4fEV8cvY/vsUxU2puQ6TP2
            9o2yIVw+U3UNTNzL7Nl+lplXH7QMntOOyDgP6MxV4pBD6zGgNWxuBYKg/eV6q2u3
            qaOdauDOX6dTRpS63BkdXFi/D8wl6e8qq4EA8sxImb0pzTcxzBxQt9HIHjjCWgci
            uS9Jwbdfrd/j41ZoDV/hnd3tm/sN41RzjYDAIF+PIHz5SRJ7hwyNxz0QEC4qSFJv
            vd8u60gtlVoiyQKCAQEAwIV1bMKmBlxtN3bFrb3IQMRJTM3t9LTJHwyRlcEmIfwJ
            LKk+oCUvtH05Ajgq2EGV1O7ZQtu3CGEw9s2RRCYo2ojh56Q6NDUQFAJtnywBZdp6
            iyGHcKrVGVXLDD97TvyTJU2n9/jPWnTIXXuZquihAaTIhCFd6a/9lim0tIwALTTv
            7oVH2co2eq4uBAqH0hDUL23woN7Rr5A9wiyJc0xs5Il8ThGX1yQsWTdmDRzwdv8r
            k6Eurm/5++DkjQx93Li6UIRZI0VPzwKTyJlgLIYpmbHt8Xmt+m8EE+JlygsytDQA
            du6gxqad1i3n+uO/UZjD5ho0wzyhYCVuBKDAQaofxwKCAQEAvdun9a8+rWp7M7Ok
            GFzwtDJZ3QHYL8ZBp8on54Z5MXV6Rre5EAEDui1g6uSi/EE8+HNQ0EbWlPS4Ken/
            g3UP3mJikFKDJW5CKCdCcnJzxBZdc+zn+jimTA78ujDs4VH7+2u/65LfU6oYqX7V
            L1ZzEHjOCwcVsT5EM5E+rF5lrb5OkpAIhIXgGIU6oNQMNnAWUzleUhNVYNInJMo0
            KosuE2SHjyQLuO7kSGD4ggWGphsQwh9K72N/NGveUGdUpzvJxrOAPzh/BEUfWt6l
            e6QeZhl9LAoZSWh1q2fBVLEU9cAcNNCkRhjEZFNji8L2/Ume4vZRxHsd/51x4uZ0
            LejxsQKCAQANv3oLMjs46RDDjS/AoHTUay/w1CPR/bb/CJ682vYmJyFglxVpyj4F
            3YtcpTYqC0Tv176cD6SabJZaiYN+Ilt4f53iNNATOlbTlvjNDQ9sfpWRqetKGGjv
            TjkZvs7HbTH0z/7WrmXgR8anJlRq6AHXZDUNenSCY5bwSjolSnoYwFcB6XKgEtih
            Gh8fGsFoNttwJ6GvWzoOF3bRjuyh1ytPhqHh0U/OhT7FgDdBaHejh8VM3Y2/1y86
            1Wx8xg+W23oylcDny+NPHRgAkzNS+qGt4A7l15Kc96CK6vfp3bLZO31tAM1qYiuT
            R+Pw/qKC6S3UGLr71jCP9RxOKEySY9uxAoIBAHvazQ0NZMqEcUk/RMfI/h8ujtES
            6BH/vNpPwRKBKLtcn9nqgQA+SdmEIqRlrw75xpUHTXZ0g4i5ru5+iBA8zsmdlGnA
            fDyfiJ0EPkvZhj3J++33tvorX1Wrmeop1N1Jx14Qu/L4KCSZXJHiPpVUqr7WtT7p
            f1iSkhrvcn5A2XVJ/vrjqDNfB3/sBzUqIT/QJnWrxCMbSVAVh9SmtvaQ4D3hb98w
            ZYEtUeDk2LgbxZ3VgMrTTnVOVFe60OF0l7o0Fd6SfZ9bSgQqIoxX98THexGK/9DK
            ZvVsvIpNyXZFRDhykI7VQvlLE70H2mKOP81HgilqVnMhjmzSg0H+FU+7MsI=
            -----END RSA PRIVATE KEY-----
